### PR TITLE
Mark as deprecated

### PR DESCRIPTION
**Pull request by meltsufin**
@arouzrokh @ludoch PTAL

### CODE REVIEW

**Comment by arouzrokh** [comment]
'Ship it'

**Comment by ludoch** [comment]
None of the github Cloud samples are using the new plugin, so let's wait
for when they are updated (and tested with the new plugin).
It seems that the public doc is sometimes affected by the same pattern (doc
not aligned with samples).

**Comment by meltsufin** [comment]
The public docs have been updates, but I'm not sure what is the state of the samples. @lesv

**Comment by ludoch** [comment]
I think this is the core of the issue. For example, If I follow the public
doc for Jetty9 compat, I end up with a failed tutorial, mixing the 2 things.

**Comment by lesv** [comment]
Some docs are confused -- they will be fixed today.

**Comment by lesv** [comment]
This shouldn't happen yet -- Endpoints v2 requires a feature here.

**Comment by meltsufin** [comment]
The old appengine-maven-plugin supports endpoints. That plugin is not being deprecated yet. So, I don't think there is a feature gap if this plugin is deprecated. @arouzrokh

**Comment by lesv** [comment]
This is for the NEW endpoints, and there will be other features where this is important.

This is about the gcloud maven plugin deprecation.

**Comment by arouzrokh** [comment]
@lesv I think with the latest updates, we can push ahead with marking this as deprecated? let me know what else is remaining (with the exception of Beta flag which for now is tabled because we are thinking of a different strategy, possibly a beta plugin, for beta releases)

**Comment by lesv** [comment]
We are close, just not yet.  We haven't released the new EP plugins.

**Comment by arouzrokh** [comment]
We've pretty much updated all branches and for GAE Standard we are still supporting the old plugin here: https://github.com/GoogleCloudPlatform/appengine-maven-plugin

Please merge this PR. Thanks.

**Comment by meltsufin** [comment]
@ludoch ping... can you please merge this?

**Pull request merged**
